### ISSUE TITLE
Update to latest?

### ISSUE THREAD

**Issue by joetheday** [jchavarri/framerjs-prebuilt#2]
Hey @jchavarri, I'm doing quite a bit of work on Framer on PC right now and can help keep this up to date. What would be the best way to do that? Just fork and submit a pull request?

**Comment by jchavarri** [comment]
Hey @joetheday, yes, feel free to open a PR with the newest version. I only used this repo during just a project that already ended, but happy to merge any updates you might need.

**Comment by joetheday** [comment]
Excellent. I'm not quite sure what to do with the Version.coffee file. It says it's automatically generated, but how that happens is the part I'm not getting. I'll put up a PR with just the framer files updated, and if there's anything else I need to do let me know.
